[EC-34] Create a docker image and push to the docker container registry

diff --git a/.github/workflows/build-and-deploy-to-dev-environment.yml b/.github/workflows/build-and-deploy-to-dev-environment.yml
--- a/.github/workflows/build-and-deploy-to-dev-environment.yml
+++ b/.github/workflows/build-and-deploy-to-dev-environment.yml
@@ -78,6 +78,12 @@ jobs:
       NAMESPACE: ${{ vars.DOCKER_HUB_USERNAME }}
       IMAGE_NAME: ${{ vars.DOCKER_HUB_REPOSITORY }}
     steps:
+      - name: Validate required variables
+        run: |
+          if [ -z "${{ vars.DOCKER_HUB_REPOSITORY }}" ]; then
+            echo "Error: DOCKER_HUB_REPOSITORY is not set."
+            exit 1
+          fi
       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
@@ -89,3 +95,26 @@ jobs:
           registry: ${{ env.CONTAINER_REGISTRY }}
           username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
           password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}
+      - name: Extract metadata (tags, labels) for Docker
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          images: |
+            ${{ env.CONTAINER_REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
+          tags: |
+            type=semver,pattern={{version}},value=${{ inputs.version }}
+            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
+            type=semver,pattern={{major}},value=${{ inputs.version }}
+            type=ref,event=branch,suffix=-{{ sha }}
+            type=ref,event=pr
+            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
+      - name: Build and push Docker Image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./Dockerfile
+          push: ${{ github.event_name != 'pull_request' }}
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          build-args: |
+            JAR_FILE=${{ needs.build.outputs.jar_file_name }}
